name: GoRest API
on:
  workflow_dispatch
  
jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      # Run the POSTMAN collection
      - name: Run POSTMAN collection
        run: |
          newman run Go_Rest_collection.json -e Go_Rest_environment.json 



     
