name: GoRest API
on:
  workflow_dispatch
  
jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
        # INstall Node on the runner
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"


      # Install the newman command line utility and also install the html extra reporter
      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
      
      # Run the POSTMAN collection
      - name: Run POSTMAN collection
        run: |
          newman run Go_Rest_collection.json -e Go_Rest_environment.json 



     
